### ISSUE TITLE
Icarus Server Startup

### ISSUE THREAD

**Issue by Ucda1212** [RocketWerkz/IcarusDedicatedServer#3]
I put the config file in WindowsServer folder location, but the name, password, and everything else doesn't appear. When I go into the dedicated server list it doesn't appear. Can't find it anywhere.

**Comment by Element21302** [comment]
Try adding  -SteamServerName="[name]" to the command line instead. Currently the SessionName in the config file does nothing.
Forward ports on your router as well if you have not yet.

**Comment by Ucda1212** [comment]
> Try adding -SteamServerName="[name]" to the command line instead. Currently the SessionName in the config file does nothing. Forward ports on your router as well if you have not yet.

I think I'm in over my head. Got no idea what that means or how to do it. I'm see on buying servers.

**Comment by Element21302** [comment]
Its super simple. 
Create a file named "start_server.bat" in the same folder as the .exe.
Add this to it.

`IcarusServer.exe -Log -SteamServerName="Your Server Name"`

Use the bat file to start the server.

All the other settings can be applied to the ServerSettings.ini file.

**Comment by Ucda1212** [comment]
> 

Yes, I started the server with this, still can't find it in the dedicated servers tab, and how do I forward ports?

**Comment by CaptainFOX2** [comment]
i have the same problem
i did PF for 17777 and 27015
my start up look like this          IcarusServer -log -SteamServerName="FOX ICARUS" -PORT="27015"
i start the bat file, wait for all the commands lines to finish and the last one look like this 

[2022.12.16-09.00.19:003][337]LogIcarusGameModeSurvival: --------  Server is now empty  --------

and when i try to find it... nothing

i don't know if is good or not, what do you think guys?

**Comment by Element21302** [comment]
Make sure the correct ports are forwarded in your router as well as making exceptions in windows firewall.

[https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/](https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/)

[https://lexisnexis.custhelp.com/app/answers/answer_view/a_id/1081611/~/adding-exceptions-to-the-windows-firewall](https://lexisnexis.custhelp.com/app/answers/answer_view/a_id/1081611/~/adding-exceptions-to-the-windows-firewall)
